services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app  # Монтируем папку server в /app контейнера
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    depends_on:
      - server
    volumes:
      - ./client:/app  # Монтируем папку client в /app контейнера
    networks:
      - app-network

networks:
  app-network:
    driver: bridge